name: "CodeQL - project 2"

on:
  push:
    branches: [ "main" ]
    paths:
      - 'project2/**'
      - '.github'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'project2/**'
      - '.github/**'

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        project: [ 'project2' ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Initialize CodeQL for ${{ matrix.project }}
      uses: github/codeql-action/init@v2
      with:
        languages: javascript
        config-file: .github/${{ matrix.project }}-config.yml

    - name: Autobuild
      uses: github/codeql-action/autobuild@v2

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
      with:
        category: "${{ matrix.project }}"              # this makes sure that analysis results are not overwritten by later analyses
